# This file is the entry point to configure your own services.
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\Document\DocumentFileManager:
        arguments:
            $templatesDir: '%kernel.project_dir%/templates/documents/'
            $outputDir: '%kernel.project_dir%/public/generated_docs/'

    _instanceof:
        App\Service\Document\DocumentGeneratorInterface:
            tags: ['app.document_generator']

    App\Service\DocumentGeneratorFactory:
        bind:
            $generators: !tagged_iterator app.document_generator

    App\Service\HealthCheck\HealthCheckService:
        arguments:
            $templatesDir: '%kernel.project_dir%/templates/documents/'
            $version: '1.0.0'

    App\Service\Document\DocumentConversionService:
        arguments:
            $conversionEndpoint: '%env(CONVERSION_ENDPOINT)%'